[build]
  command = "next build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NEXT_FORCE_HYDRATEROOT = "true"

# Configure Next.js cache
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = false
  minify = false

[build.processing.js]
  bundle = false
  minify = false

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# Cache settings
[[redirects]]
  from = "/_next/static/*"
  to = "/static/:splat"
  status = 200
  force = true

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
